export const ORDER_STATE = {
  PLACED: 'ORDER_PLACED',
  CANCELLED: 'ORDER_CANCELLED',
  ACCEPTED: 'ORDER_ACCEPTED',
  REJECTED: 'ORDER_REJECTED',
  OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  DELIVERED: 'ORDER_DELIVERED',
}